version: '3.5'

services:
  nextjs:
    container_name: nextjs
    build:
      context: .
    command: ["npm", "run", "start"]
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000