"use client"

import Image from "next/image";
import { useState } from "react";

interface Props {
    handleSendDialog: (object: {nom: string, text: string}[]) => any;
}

const Pharmacie = (props: Props) => {
    
    const handleClick = () => {
        props.handleSendDialog([
            {
                nom: "Narrateur",
                text: "Le Héro entre dans la pharmacie" 
            },
            {
                nom: "Héro",
                text: "Bonjour ! Ce serait pour acheter des protections sexuelles car je souhaite passez le cap avec mon/ma copain/copine."
            },
            { 
                nom: "Pharmacien",
                text: "bonjour jeune homme/jeune femme, voici une gamme de protections sexuelles, je vous laisses choisir" 
            },
        ]);
    }
    

    return (
        <div className="flex flex-col relative w-2/3 mx-auto">
            <Image src="/pharma.png" className="absolute" alt="img" width="600" height="600" />
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100" onClick={e => handleClick()}><Image src="/perso1.png" className="absolute" alt="img" width="24" height="24" /></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100" onClick={e => handleClick()}><Image src="/perso2.png" className="absolute" alt="img" width="24" height="24" /></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div><div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
            <div className="flex z-10">
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
                <div className="w-6 h-6  border-black-100"></div>
            </div>
        </div>
    );
};

export default Pharmacie;